from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    Boolean,
    DateTime,
    Index
)

from datetime import datetime

from config.database import Base


class Transaction(Base):
    """
    Financial transaction table.
    Stores all transaction records for fraud analysis.
    """

    __tablename__ = "transactions"

    # Primary Key
    id = Column(Integer, primary_key=True, index=True)

    # Business transaction identifier
    transaction_id = Column(String, unique=True, nullable=False)

    # Customer/User identifier
    user_id = Column(String, nullable=False, index=True)

    # Transaction amount
    amount = Column(Float, nullable=False)

    # Merchant category
    merchant_category = Column(String, nullable=False, index=True)

    # Transaction timestamp
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    # Geographic location
    location = Column(String, nullable=False)

    # Fraud label (used for ML training)
    is_fraud = Column(Boolean, default=False)

    # Risk score generated by ML model
    risk_score = Column(Float, default=0.0)

    risk_level = Column(String)

    transaction_hour = Column(Integer)

    day_of_week = Column(String)

    is_high_risk_merchant = Column(Integer)

    amount_log = Column(Float)

    amount_category = Column(String)

    # Alert status
    alert_status = Column(String, default="OPEN")

    # Composite indexes for analytics optimization
    __table_args__ = (
        Index("idx_user_timestamp", "user_id", "timestamp"),
        Index("idx_fraud_risk", "is_fraud", "risk_score"),
        Index("idx_amount", "amount"),
        Index("idx_location", "location"),
        Index("idx_merchant", "merchant_category"),
    )

    def __repr__(self):
        return (
            f"<Transaction(transaction_id={self.transaction_id}, "
            f"amount={self.amount}, fraud={self.is_fraud})>"
        )